name: Cleanup Images

on:
    workflow_dispatch:
    schedule:
        - cron: '0 3 * * *'

permissions:
    packages: write

jobs:
    cleanup:
        name: Cleanup Old Images
        runs-on: ubuntu-latest
        steps:
            -   name: Prune untagged images
                uses: dataaxiom/ghcr-cleanup-action@v1
                with:
                    package: docker
                    token: ${{ secrets.GITHUB_TOKEN }}
                    # Delete untagged images older than 14 days
                    delete-untagged: true
                    older-than: 14 days
                    # Keep at least 3 untagged images as safety buffer
                    keep-n-untagged: 3
